{
  "formatVersion": "1.1",
  "component": {
    "group": "org.altbeacon",
    "module": "android-beacon-library",
    "version": "2.20.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "android-beacon-library-2.20.0.aar",
          "url": "android-beacon-library-2.20.0.aar",
          "size": 242153,
          "sha512": "309975f7115c7c73e5f1ed9ab3bf90b6ceb6bc7efeea37d15f8b30f27544cc88730f6c96ca87374a2b74d949808c0cc40e7d35d7cc334ac98d01f98421ea1c6b",
          "sha256": "091fbfc429c0a0870b6833a019a55b659aa5219e87c4172a4f53e0293d6df0cd",
          "sha1": "f864d8d0a82b669c0f64990f060ecebde0ce1033",
          "md5": "76ceb397ed83b7802e36d9a3b4228a42"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.localbroadcastmanager",
          "module": "localbroadcastmanager",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "android-beacon-library-2.20.0.aar",
          "url": "android-beacon-library-2.20.0.aar",
          "size": 242153,
          "sha512": "309975f7115c7c73e5f1ed9ab3bf90b6ceb6bc7efeea37d15f8b30f27544cc88730f6c96ca87374a2b74d949808c0cc40e7d35d7cc334ac98d01f98421ea1c6b",
          "sha256": "091fbfc429c0a0870b6833a019a55b659aa5219e87c4172a4f53e0293d6df0cd",
          "sha1": "f864d8d0a82b669c0f64990f060ecebde0ce1033",
          "md5": "76ceb397ed83b7802e36d9a3b4228a42"
        }
      ]
    }
  ]
}
